version: '3.9'

volumes:
    deepstream:
        external: True

services:
    deepstream-app:
        build:
            context: .
            dockerfile: Dockerfile
        # image: deepstream-app:latest

        user: root
        container_name: deepstream-app
        volumes: 
            - deepstream:/workspace

